import { supabase } from "@/integrations/supabase/client";

// HiveTrace domain model + demo data with real SHA-256 hash chaining (demo-grade,
// computed client-side for the prototype; production would hash server-side).

export const STAGES = [
  "beekeeper",
  "harvesting",
  "testing",
  "processing",
  "packaging",
  "distribution",
] as const;

export type StageKey = (typeof STAGES)[number];

export type Role =
  | "beekeeper"
  | "tester"
  | "processing"
  | "distribution"
  | "admin";

export interface StageMeta {
  key: StageKey;
  label: string;
  icon: string;
  editableBy: Role[];
  editableByLabel: string;
  fields: { key: string; label: string; placeholder?: string }[];
}

export const STAGE_META: StageMeta[] = [
  {
    key: "beekeeper",
    label: "Beekeeper",
    icon: "🧑‍🌾",
    editableBy: ["beekeeper"],
    editableByLabel: "Beekeeper",
    fields: [
      { key: "beekeeperId", label: "Beekeeper ID", placeholder: "BK001" },
      { key: "beekeeperName", label: "Beekeeper name" },
      { key: "hiveId", label: "Hive ID", placeholder: "H-042" },
      { key: "apiaryLocation", label: "Apiary location" },
    ],
  },
  {
    key: "harvesting",
    label: "Harvesting",
    icon: "🍯",
    editableBy: ["beekeeper"],
    editableByLabel: "Beekeeper",
    fields: [
      { key: "harvestDate", label: "Date of harvesting", placeholder: "2026-03-12" },
      { key: "quantityKg", label: "Quantity (kg)" },
      { key: "hiveInfo", label: "Hive info" },
    ],
  },
  {
    key: "testing",
    label: "Testing",
    icon: "🧪",
    editableBy: ["tester"],
    editableByLabel: "Lab / Tester",
    fields: [
      { key: "testingDate", label: "Testing date", placeholder: "2026-09-06" },
      { key: "moisturePct", label: "Moisture (%)" },
      { key: "purityPct", label: "Purity (%)" },
      { key: "testResult", label: "Test result", placeholder: "Pass / Fail / Pending" },
    ],
  },
  {
    key: "processing",
    label: "Processing / Extraction",
    icon: "⚙️",
    editableBy: ["processing"],
    editableByLabel: "Processing Facility",
    fields: [
      { key: "processingDate", label: "Processing date" },
      { key: "facility", label: "Facility" },
    ],
  },
  {
    key: "packaging",
    label: "Packaging",
    icon: "📦",
    editableBy: ["distribution"],
    editableByLabel: "Packaging & Distribution",
    fields: [
      { key: "packagingDate", label: "Packaging date" },
    ],
  },
  {
    key: "distribution",
    label: "Distribution",
    icon: "🚚",
    editableBy: ["distribution"],
    editableByLabel: "Packaging & Distribution",
    fields: [
      { key: "shipment", label: "Shipment / courier" },
      { key: "destination", label: "Destination" },
    ],
  },
];

export interface DemoUser {
  id: string;
  name: string;
  email: string;
  role: Role;
  roleLabel: string;
  beekeeperId?: string;
}

export const DEMO_USERS: DemoUser[] = [
  { id: "u-bee", name: "Maya Deori", email: "maya@honeychain.in", role: "beekeeper", roleLabel: "Beekeeper / Field Staff", beekeeperId: "BK001" },
  { id: "u-lab", name: "Dr. Arjun Rao", email: "arjun@honeylab.in", role: "tester", roleLabel: "Lab / Tester" },
  { id: "u-proc", name: "Sunita Kashyap", email: "sunita@purehive.in", role: "processing", roleLabel: "Processing Facility" },
  { id: "u-dist", name: "Rohan Baruah", email: "rohan@hivedist.in", role: "distribution", roleLabel: "Packaging & Distribution" },
  { id: "u-admin", name: "HiveTrace Admin", email: "admin@honeychain.in", role: "admin", roleLabel: "Admin (view only)" },
];

export interface ChainRecord {
  id: string;
  batchId: string;
  stage: StageKey;
  data: Record<string, string>;
  prevHash: string;
  hash: string;
  createdBy: string;
  createdAt: string;
  superseded?: boolean;
}

export interface Batch {
  /** Database row id. */
  uuid: string;
  /** Public batch code shown on the jar (HC1025). */
  id: string;
  /** Production batch number generated by the database at harvest. */
  batchNo?: string | null;
  hiveId: string;
  apiaryLocation: string;
  createdBy: string;
  createdAt: string;
  records: ChainRecord[];
}

// ---------- hashing ----------

function stableStringify(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`;
  const obj = value as Record<string, unknown>;
  return `{${Object.keys(obj)
    .sort()
    .map((k) => `${JSON.stringify(k)}:${stableStringify(obj[k])}`)
    .join(",")}}`;
}

export async function sha256Hex(input: string): Promise<string> {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(input));
  return Array.from(new Uint8Array(buf))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

export async function computeRecordHash(r: {
  batchId: string;
  stage: string;
  data: Record<string, string>;
  prevHash: string;
  createdAt: string;
}): Promise<string> {
  // Timestamps are normalised so a hash stays stable regardless of how the
  // database formats the stored value ("2026-03-02 05:40:00+00" vs ISO).
  const ts = Number.isNaN(Date.parse(r.createdAt)) ? r.createdAt : new Date(r.createdAt).toISOString();
  return sha256Hex(r.prevHash + "|" + r.batchId + "|" + r.stage + "|" + stableStringify(r.data) + "|" + ts);
}

// ---------- database-backed batches ----------

export async function loadBatches(): Promise<Batch[]> {
  const [batchRes, recordRes] = await Promise.all([
    supabase
      .from("batches")
      .select("id, code, hive_id, apiary_location, created_by_name, created_at, batch_no")
      .order("created_at", { ascending: true }),
    supabase
      .from("chain_records")
      .select("id, batch_id, stage, data, prev_hash, hash, created_by_name, created_at")
      .order("created_at", { ascending: true }),
  ]);
  if (batchRes.error) throw batchRes.error;
  if (recordRes.error) throw recordRes.error;

  const records = recordRes.data ?? [];
  return (batchRes.data ?? []).map((b) => ({
    uuid: b.id,
    id: b.code,
    hiveId: b.hive_id,
    apiaryLocation: b.apiary_location,
    createdBy: b.created_by_name,
    createdAt: b.created_at,
    batchNo: b.batch_no,
    records: records
      .filter((r) => r.batch_id === b.id)
      .map((r) => ({
        id: r.id,
        batchId: b.code,
        stage: r.stage as StageKey,
        data: (r.data ?? {}) as Record<string, string>,
        prevHash: r.prev_hash,
        hash: r.hash,
        createdBy: r.created_by_name,
        createdAt: r.created_at,
      })),
  }));
}

/** Creates a batch; the database assigns the batch code (HC1028, HC1029, …). */
export async function createBatchRow(
  hiveId: string,
  apiaryLocation: string,
  createdByName: string,
): Promise<Batch> {
  const { data, error } = await supabase.rpc("create_batch", {
    _hive_id: hiveId,
    _apiary_location: apiaryLocation,
    _created_by_name: createdByName,
  });
  if (error) throw error;
  const row = data as {
    id: string;
    code: string;
    hive_id: string;
    apiary_location: string;
    created_by_name: string;
    created_at: string;
    batch_no: string | null;
  };
  return {
    uuid: row.id,
    id: row.code,
    hiveId: row.hive_id,
    apiaryLocation: row.apiary_location,
    createdBy: row.created_by_name,
    createdAt: row.created_at,
    batchNo: row.batch_no,
    records: [],
  };
}

/** Appends a stage entry to the batch's hash chain in the database. */
export async function appendChainRecord(
  batch: Batch,
  entry: {
    stage: StageKey;
    data: Record<string, string>;
    createdBy: string;
    createdAt: string;
  },
): Promise<ChainRecord> {
  const prevHash = batch.records.at(-1)?.hash ?? "GENESIS";
  const hash = await computeRecordHash({
    batchId: batch.id,
    stage: entry.stage,
    data: entry.data,
    prevHash,
    createdAt: entry.createdAt,
  });
  const { data, error } = await supabase
    .from("chain_records")
    .insert({
      batch_id: batch.uuid,
      stage: entry.stage,
      data: entry.data,
      prev_hash: prevHash,
      hash,
      created_by_name: entry.createdBy,
      created_at: entry.createdAt,
    })
    .select("id")
    .single();
  if (error) throw error;
  return {
    id: data.id,
    batchId: batch.id,
    stage: entry.stage,
    data: entry.data,
    prevHash,
    hash,
    createdBy: entry.createdBy,
    createdAt: entry.createdAt,
  };
}

/** Arrival confirmations, keyed as `${batchCode}:${stage}`. */
export async function loadArrivals(): Promise<Record<string, string>> {
  const { data, error } = await supabase
    .from("batch_arrivals")
    .select("stage, created_at, batches(code)");
  if (error) throw error;
  const out: Record<string, string> = {};
  for (const row of data ?? []) {
    const code = (row.batches as { code: string } | null)?.code;
    if (code) out[`${code}:${row.stage}`] = row.created_at;
  }
  return out;
}

export async function confirmArrival(
  batch: Batch,
  stage: StageKey,
  confirmedByName: string,
): Promise<string> {
  const { data, error } = await supabase
    .from("batch_arrivals")
    .insert({ batch_id: batch.uuid, stage, confirmed_by_name: confirmedByName })
    .select("created_at")
    .single();
  if (error) throw error;
  return data.created_at;
}

export function stageComplete(batch: Batch, stage: StageKey): boolean {
  const meta = STAGE_META.find((m) => m.key === stage)!;
  const latest = latestRecord(batch, stage);
  if (!latest) return false;
  return meta.fields.every((f) => (latest.data[f.key] ?? "").trim() !== "");
}

export function latestRecord(batch: Batch, stage: StageKey): ChainRecord | undefined {
  const recs = batch.records.filter((r) => r.stage === stage && !r.superseded);
  return recs[recs.length - 1];
}

export function completedStageCount(batch: Batch): number {
  return STAGES.filter((s) => stageComplete(batch, s)).length;
}

export interface VerifyResult {
  intact: boolean;
  checked: number;
  brokenAt?: { stage: StageKey; recordId: string };
}

export async function verifyChain(batch: Batch): Promise<VerifyResult> {
  let prevHash = "GENESIS";
  for (const r of batch.records) {
    const expected = await computeRecordHash({
      batchId: r.batchId,
      stage: r.stage,
      data: r.data,
      prevHash,
      createdAt: r.createdAt,
    });
    if (r.prevHash !== prevHash || expected !== r.hash) {
      return { intact: false, checked: batch.records.length, brokenAt: { stage: r.stage, recordId: r.id } };
    }
    prevHash = r.hash;
  }
  return { intact: true, checked: batch.records.length };
}

export function shortHash(hash: string): string {
  return hash === "GENESIS" ? "GENESIS" : hash.slice(0, 10) + "…" + hash.slice(-6);
}

export function formatDate(iso: string): string {
  return new Date(iso).toLocaleString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

// ---------- auto-generated production batch numbers ----------
// Format: <hive-id>-<beekeeper-id>-<harvest date YYYYMMDD>-<running batch no.>
// e.g. H-107-BK001-20260906-005

/** Asks the database to generate + store the production batch number for a harvested batch. */
export async function assignBatchNo(batch: Batch): Promise<string | null> {
  const bee = latestRecord(batch, "beekeeper");
  const harvest = latestRecord(batch, "harvesting");
  const { data, error } = await supabase.rpc("assign_batch_no", {
    _batch_id: batch.uuid,
    _hive_id: bee?.data['hiveId'] || batch.hiveId,
    _beekeeper_id: bee?.data['beekeeperId'] || "BK000",
    _harvest_date: harvest?.data['harvestDate'] || "",
  });
  if (error) throw error;
  return data as string | null;
}
